### ISSUE TITLE
[Feature Request]: GetAll method

### ISSUE THREAD

**Issue by tzdybal** [rollkit/go-da#10]
### Implementation ideas

Currently there is no way to get blobs without knowing it's exact ID - this prohibits any form of scanning DA layer.

Proposed solution is to add following method:
```go
type DA interface {
// ... 
    GetAll(daHeight uint64) ([]Blob, error)
// ...
}
```

Implementation of this method should return all the blobs found in DA layer at given height.

**Comment by tzdybal** [comment]
`GetAll` can be implemented using `GetIDs(height)` and `Get` - this is more flexible approach.

**Comment by nashqueue** [comment]
Should it not be something like  GetIDs(height , namespace ) ? Or maybe the namespace as an optional parameter ?
