### ISSUE TITLE
[Feature Request]: Add a SyncWait method

### ISSUE THREAD

**Issue by tuxcanfly** [rollkit/go-da#20]
### Implementation ideas

Implementation ideas
Currently there is no way to wait before the remote node is synced so that we can start submitting blobs.

Proposed solution is to add following method:

```
type DA interface {
// ... 
    SyncWait() (error)
// ...
}
```

Implementation of this method should transparently call `Header.SyncWait`

**Comment by Wondertan** [comment]
In case of celestia-node, you don't have to wait until it synced and can start submitting asap.

**Comment by Wondertan** [comment]
In general, Celestial-node is designed so that you can use any of the APIs without external assumptions like node is synced or not. If needed, the API call will wait internally for the required state.
