### ISSUE TITLE
[Feature Request]: Add namespace / appID as optional parameter to Submit function 

### ISSUE THREAD

**Issue by nashqueue** [rollkit/go-da#33]
### Implementation ideas

In order to implement go-da directly into celestia-node, setting namespace as a global parameter is not a viable option. Additionally, it restricts the possibility for clients to use multiple namespaces without instantiating multiple clients. To fix this, we can add a field `SubmitOptions` to the Submit signature.

**Comment by nashqueue** [comment]
cc @distractedm1nd

**Comment by Wondertan** [comment]
From our quick with @distractedm1nd we decided to look into embedding namespaces into IDs. You could make it part of the interface via options, but that leaks the abstraction, as only some DA have namespaces. I believe the original idea for such an edge cases was to embed such data in implementation-specific IDs

**Comment by nashqueue** [comment]
IDs are posted on-chain so I would keep that as minimal as possible. I would give more options to submit. In the future, there could be even more preferences encoded in those options like priority, top of block, TTL, etc, which not every DA-Layer has. Is see Namespace just as one of those preferences.

**Comment by Wondertan** [comment]
* IDs dont **have** to go on chain afaiu
* namespace identifies data, its not just preference

**Comment by Wondertan** [comment]
However there is no way to pass ID to submit right now. It only accepts alias to bytes which is Blob type. This is very limiting and in order to make the abstraction completer, the Blob type would need to be promoted to interface with ID method. This is though for a later refactoring.

**Comment by distractedm1nd** [comment]
I contemplated the following options:
- Extend go-da interface locally on node with an endpoint that allows setting a namespace
- Have celestia-node parse namespace from a config or cli
- having namespace at the beginning of every blob and making node parse it out
- Extending submit with an option to set namespace.
 
DA layers dont need to support namespaces of course, but it will also be good for the avail impl for example
