### ISSUE TITLE
Enable go-da to utilize multi accounts support from celestia-node

### ISSUE THREAD

**Issue by tzdybal** [rollkit/go-da#93]
Imagine following use case:
 - there is a shared celestia-node instance, providing DA for multiple rollups (operated by single org or even RasS provider, so they can setup keyring properly)
 - each rollup need to use different key

Currently there is no way in go-da to specify key name. Possible solutions are:
 - add key name as an option to `Submit` method (see: #89)
 - add generic (`[]byte`) param to `Submit` to enable passing any options
 - add new method `SubmiWithOptions` with generic (`[]byte`) options
 - add `SetKeyName` method to go-da interface
 - add generic `SetConfig([]byte)` method to go-da interface
 - leave go-da interface as is and extend [`proxy.GetClient`](https://github.com/rollkit/go-da/blob/67c3cff55885201aba819affaf9a56ee55103ee2/proxy/client.go#L18) to enable passing more options
   - actually the `token` is already similar use case (but seems way more generic than key name)
 

This is somehow similar to `MaxBlobSize` but the other way around. go-da interface is focused strictly on DA operation and not on life-cycle / metadata /  configuration.

**Comment by tuxcanfly** [comment]
Another possible solution is to add a new method e.g. `SubmitWithOptions(... Options []byte)` which just forwards the options as a opaque bytestring to be decoded by the server.
